package com.mvp.wangll.mvptest.greenDao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mvp.wangll.mvptest.demo.list.bean.UserBean;
import com.mvp.wangll.mvptest.Httpframework.fileDownLoad.DownInfo;

import com.mvp.wangll.mvptest.greenDao.UserBeanDao;
import com.mvp.wangll.mvptest.greenDao.DownInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userBeanDaoConfig;
    private final DaoConfig downInfoDaoConfig;

    private final UserBeanDao userBeanDao;
    private final DownInfoDao downInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        downInfoDaoConfig = daoConfigMap.get(DownInfoDao.class).clone();
        downInfoDaoConfig.initIdentityScope(type);

        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);
        downInfoDao = new DownInfoDao(downInfoDaoConfig, this);

        registerDao(UserBean.class, userBeanDao);
        registerDao(DownInfo.class, downInfoDao);
    }
    
    public void clear() {
        userBeanDaoConfig.clearIdentityScope();
        downInfoDaoConfig.clearIdentityScope();
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

    public DownInfoDao getDownInfoDao() {
        return downInfoDao;
    }

}
